services:
  satis:
    image: dockerhub.fidy.net/fidy_tools/satis:latest
    container_name: satis
    hostname: satis
    restart: unless-stopped
    ports: 
      - "8091:80"
    volumes:
      - "./composer_cache:/var/www/.composer"
      - "./www:/var/www"
      - "~/.ssh/id_rsa:/var/tmp/id"
      - "./config:/satisfy/config_tmp"
      - "./nginx/passwd:/home/passwd"
      - "./log:/var/log"
    environment:
      PRIVATE_REPO_DOMAIN_LIST: github.com
      CRONTAB_FREQUENCY: "5 3 * * *"
      VIRTUAL_HOST: ${VHOST}
